In [27]:
import tensorflow as tf
import numpy as np

In [36]:
a = np.array([[4,2],
              [3,8]])

In [37]:
2 * np.square(a)

array([[ 32,   8],
       [ 18, 128]])

In [38]:
2 * a * a

array([[ 32,   8],
       [ 18, 128]])

In [ ]:
h = W * X * X + b

In [31]:
my_data = np.genfromtxt('test.csv', delimiter=',')
x_data = my_data[0]
y_data = my_data[1]

In [5]:
W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [6]:
X = tf.placeholder(tf.float32, shape=[None])
Y = tf.placeholder(tf.float32, shape=[None])

In [7]:
hypothesis = W * X + b

In [8]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
np.gradient(cost)

In [10]:
train = optimizer.minimize(cost)

In [11]:
sess = tf.Session()

In [32]:
sess.run(tf.global_variables_initializer())

In [33]:
for step in range(2000):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict={ X: x_data, Y: y_data })
    
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 191.623 [ 1.61533916] [-1.58746052]
20 1.23615 [ 2.34295297] [-1.24723709]
40 1.02224 [ 2.31187105] [-1.04356968]
60 0.845343 [ 2.28360605] [-0.85836047]
80 0.699059 [ 2.25790286] [-0.68993688]
100 0.57809 [ 2.23452902] [-0.53677756]
120 0.478053 [ 2.21327376] [-0.39749905]
140 0.395328 [ 2.19394445] [-0.27084345]
160 0.326918 [ 2.17636728] [-0.15566659]
180 0.270345 [ 2.16038322] [-0.05092831]
200 0.223563 [ 2.14584756] [ 0.04431748]
220 0.184876 [ 2.13262939] [ 0.13093115]
240 0.152884 [ 2.12060905] [ 0.20969506]
260 0.126428 [ 2.10967827] [ 0.28132063]
280 0.10455 [ 2.09973812] [ 0.34645471]
300 0.086458 [ 2.09069896] [ 0.40568566]
320 0.0714968 [ 2.08247876] [ 0.45954853]
340 0.0591244 [ 2.07500362] [ 0.50852984]
360 0.0488932 [ 2.06820607] [ 0.55307198]
380 0.0404325 [ 2.06202459] [ 0.59357703]
400 0.0334356 [ 2.0564034] [ 0.63041115]
420 0.0276498 [ 2.05129147] [ 0.66390699]
440 0.0228651 [ 2.04664302] [ 0.69436711]
460 0.0189084 [ 2.04241562] [ 0.72206664]
480 0.0156363 [ 2.03

In [34]:
def myH(x):
    return W_val * x + b_val

In [35]:
myH(350)[0]

701.00964

In [42]:
b_val

array([ 0.99981529], dtype=float32)